import os
import numpy as np
import torch
import matplotlib.pyplot as plt

from simulator.model import Model


def visualize_channel(args):
    """Visualize distributions of z, z_hat (labeled), and z_hat generated by the Model."""
    path_data = os.path.join(args.dataset_dir, 'channel_io.npz')
    if not os.path.exists(path_data):
        raise FileNotFoundError(f'Dataset not found: {path_data}')

    data = np.load(path_data)
    Z = np.asarray(data['Z'], dtype=np.complex64)       # (N, 64)
    Z_hat = np.asarray(data['Z_hat'], dtype=np.complex64)

    # Load model
    model_dir = os.path.join(args.model_dir, 'channel_io_rayleigh_awgn')
    path_ckpt = os.path.join(model_dir, 'model_best.pth.tar')
    model = Model(args).to(args.device)
    if os.path.exists(path_ckpt):
        ckpt = torch.load(path_ckpt, map_location=args.device, weights_only=False)
        model.load_state_dict(ckpt['state_dict'] if 'state_dict' in ckpt else ckpt)
        model.eval()
    else:
        model.eval()

    # Generate z_hat from model: z_hat_gen = Model(z)
    batch_size = getattr(args, 'batch_size', 64)
    z_hat_gen_list = []
    with torch.no_grad():
        for i in range(0, len(Z), batch_size):
            z_batch = Z[i : i + batch_size]
            z_t = torch.from_numpy(z_batch).to(args.device)
            z_hat_gen = model(z_t)
            z_hat_gen_list.append(z_hat_gen.cpu().numpy())
    z_hat_gen = np.concatenate(z_hat_gen_list, axis=0).astype(np.complex64)

    # Flatten to (N*64,) or use one symbol for clearer plot
    sym_idx = 0
    z_flat = Z[:, sym_idx].flatten()
    z_hat_flat = Z_hat[:, sym_idx].flatten()
    z_hat_gen_flat = z_hat_gen[:, sym_idx].flatten()

    # Subsample if too many points for scatter
    max_points = 2000
    n = len(z_flat)
    if n > max_points:
        rng = np.random.default_rng(getattr(args, 'seed', 0))
        idx = rng.choice(n, max_points, replace=False)
        z_flat = z_flat[idx]
        z_hat_flat = z_hat_flat[idx]
        z_hat_gen_flat = z_hat_gen_flat[idx]

    fig, axes = plt.subplots(1, 3, figsize=(12, 4), sharex=False, sharey=False)

    def scatter_complex(ax, c, title, color='C0', alpha=0.5):
        ax.scatter(c.real, c.imag, s=8, alpha=alpha, c=color, edgecolors='none')
        ax.set_xlabel('Real')
        ax.set_ylabel('Imag')
        ax.set_title(title)
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        ax.axhline(0, color='k', linewidth=0.5)
        ax.axvline(0, color='k', linewidth=0.5)

    scatter_complex(axes[0], z_flat, 'z (input)', color='C0')
    scatter_complex(axes[1], z_hat_flat, 'z_hat (labeled)', color='C1')
    scatter_complex(axes[2], z_hat_gen_flat, 'z_hat (generated by Model)', color='C2')

    plt.tight_layout()
    out_path = os.path.join(args.figure_dir, 'channel_distribution.pdf')
    plt.savefig(out_path, bbox_inches='tight')
    plt.close()
    print(f'[+] Saved {out_path}')
